apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakery-api
  template:
    metadata:
      labels:
        app: bakery-api
    spec:
      containers:
        - name: bakery-api
          image: node-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service"      # Nom du service MySQL
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"               # Utilisateur root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE